version: '3'
services:
  credentia-springboot:
    container_name: credentia-springboot
    build:
      context: .
      dockerfile: Dockerfile
    image: credenita-springboot:latest
    ports:
      - 9090:9090
    depends_on:
      - mysql
    networks:
      credentia :
    restart: always

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=credentia
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=credentiaAdmin123
      - MYSQL_ROOT_PASSWORD=credentiaRoot123
    ports:
      - 3309:3306
    networks:
      credentia :
    restart: always

volumes:
  credentia:
    driver: local

networks:
  credentia:
